// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lazltqwlkipxkdncxsdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxhemx0cXdsa2lweGtkbmN4c2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM5MjY4OTUsImV4cCI6MjA5OTUwMjg5NX0.iOYV5jaEHEjVaedzpCZ_rh5WYu16J_PnY7N4t2Hi0Nk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});